# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PelnaE
author: Edgars Pelna
email: edgarspelna@gmail.com
description: Web Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pelnae.github.io" # the base hostname & protocol for your site
domain: "pelnae.github.io"
github_username:  pelnae
facebook_username: pelnae
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/page/:num"
# Build settings
markdown: kramdown
highlighter: rouge
locale: lv_LV
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
